### ISSUE TITLE
Specify that flags cannot be lists.

### ISSUE THREAD

**Issue by glatard** [boutiques/schema#18]
Not sure how to do this in the schema...

**Comment by glatard** [comment]
@tta9, I guess this can be done using JSON schema "dependencies" as you did in #40, right?

**Comment by ttaa9** [comment]
I will look again, but I was not able to do it when I tried last time. It seems like it is meant for specifying existence, rather than values. Also, the docs for the dependencies are... not totally complete.

**Comment by ttaa9** [comment]
So, indeed, dependencies cannot do it. However, it is doable via the boolean operators of the json schema (see #40).

**Comment by glatard** [comment]
@ttaa9, I guess #40 fixes this issue; is that right?

**Comment by ttaa9** [comment]
Yes it should
