### ISSUE TITLE
Type restrictions.

### ISSUE THREAD

**Issue by glatard** [boutiques/schema#19]
Type restrictions could be defined, to allow for better validation.

For instance:
* enum strings such as { "high", "medium", "low" }.
* Numbers with bounds (low and high value).
* Integers vs. float.

**Comment by ttaa9** [comment]
So maybe the first (enum) case could be done with a new type "enum" and a set of choices in a dropdown, and we could add optional tags to Number entries like "min", "max" (floats), or "integer" (true/false).

**Comment by glatard** [comment]
Yes, it makes sense.

**Comment by ttaa9** [comment]
It might also be nice to have "min-list-entries" and "max-list-entries" (only when list is true) e.g. for BET -c which seems to require a list of size 3.
