### ISSUE TITLE
Type "Flag" should be called "Boolean" ?

### ISSUE THREAD

**Issue by jbpoline** [boutiques/schema#25]
It seems that it would be more homogeneous with "string", "list", ...

**Comment by glatard** [comment]
Yes, as long as we can make a clear difference with a boolean parameter called, e.g., with "-p true".

**Comment by glatard** [comment]
Boolean options of type "-p true" are not properly supported anyway. So, there could be an alias, i.e. type can be called "Flag" (refers to a UNIX flag) or "Boolean" indiferently.

**Comment by jbpoline** [comment]
Ok - thanks.
