### ISSUE TITLE
Permit default-values in the schema to contain command-line keys for substitution

### ISSUE THREAD

**Issue by ttaa9** [boutiques/schema#30]
It would be nice, for example, to be able to reproduce the natural (default) behaviour of fsl_anat, which is to output a directory called [INPUT_FILE_NAME_WITHOUT_EXT].anat.

**Comment by glatard** [comment]
So how was this solved @ttaa9?

**Comment by ttaa9** [comment]
I didn't think it could be done very generally. Because, when the default value is written into the form for the user, it does not know the values of any of the other command line keys (because they are actually set by filling out the form). The only possible cases this seems to work is (1) substituting other default values (which doesn't really help much) and (2), in the case where there is one and only one input file parameter and if the task is launched with exactly one file, we could define a special key that would substitute that specific file. But if there are multiple file inputs (or the task is launched with multiple files) it won't know which one to substitute (since only the user knows which file should go with which argument, I think). It seemed unnecessarily complex and brittle (not to mention confusing to people outside of cbrain) to solve a small use case.

Anyway, there's probably some things I didn't think of, so if you know a way to do it nicely, please let me know.

**Comment by glatard** [comment]
I agree with you. Let's keep this in mind if the need shows up again.
