### ISSUE TITLE
Handle parameter interactions (mutual exclusivity & one-of-a-set required)

### ISSUE THREAD

**Issue by ttaa9** [boutiques/schema#31]
We may wish to allow parameters to be mutually exclusive and/or require "at least one" of several parameters. 

E.g. fsl_anat can be called either with an input directory (-d) or a single input file (-i). Currently, the approach is to have both of them be optional, but technically at least one of them is required and each should preclude the use of the other.

**Comment by glatard** [comment]
Mutual exclusivity can be implemented using 2 "disabled-by" properties.

**Comment by glatard** [comment]
This could be implemented by defining parameter "sets" or "groups" and specifying constraints in these groups. Parameter groups should have a name and a description. They are also useful to present parameters consistently in a GUI.

**Comment by ttaa9** [comment]
That would be nice, especially for programs where many parameters can only be used in certain modes. Although, at least for the fsl_anat case I mentioned above, all of the other arguments can be used, regardless of whether -d or -i is used, so they might not naturally form a group.

**Comment by glatard** [comment]
Wouldn't the group be "input data" in the case you mentioned?

**Comment by ttaa9** [comment]
Oh I see what you mean. I thought you were talking about groups of parameters that go together (e.g. parameters for each different mode of operation). So in this case, would "one-is-required" be a group property? Maybe having a property like "required-if-no-inputs" kind of like the "disabled-by-inputs" would be easier?

**Comment by glatard** [comment]
Not sure what you mean by "required-if-no-inputs". But you're right that "disabled-by-inputs" may be worth implementing for groups. This is also related to #27.

The properties of a group could be:
* mutually-exclusive: all the inputs in the group have to be optional. At runtime, only 1 can be used.
* one-is-required: all the inputs in the group have to be optional. At runtime, at least 1 must be used.

Re. #27, option "disabled-by-inputs" remains a property of a particular input, but it could become "disables-group". "required-by-input", however, should still apply to a particular input, i.e. it becomes "requires-input".

**Comment by ttaa9** [comment]
That sounds good. Groups could then be specified as arrays of IDs then, I suppose, along with those properties? Re. #27, I don't particularly mind the current naming scheme. It might be easier to just add one property "disables-group", as you said, rather than change everything.  But it matters before #280 is implemented.
