### ISSUE TITLE
Add indications on the run-time of a task.

### ISSUE THREAD

**Issue by glatard** [boutiques/schema#8]
A specific tag should be added to the schema to declare a tentative walltime of the task. Platforms could then process this to adjust the walltime of the tasks.

**Comment by ttaa9** [comment]
Maybe a very simple fix could be an optional property "estimated-wall-time" of the task which could just be a number in seconds, or an array [days, hours, minutes, seconds], etc...

**Comment by glatard** [comment]
Yes. Number in seconds is better than an array.
